GET http://localhost:4000/posts
Authorization: Bearer "eysJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJWYW4gVGllbiIsImlhdCI6MTYzMjYyNTgwNn0.WtXfcvnd_hWV57zWAkAZSz2cO7KIBGTrtmtdbACSdwo"
# Check get API (Post)_

###
POST  http://localhost:4000/login
Content-Type:  application/json

{
    "username": "admin"
}

